### PR TITLE
Login feature

### PR DESCRIPTION
**Pull request by Noboomta**

### CODE REVIEW

**Comment by Noboomta** [comment]
@lisbono2001 bro, you forgot to create a pull request **LOL**

**Comment by bhatara007** [comment]
I think he is asleep now bro @Noboomta .

**Comment by Noboomta** [comment]
404 @lisbono2001 not found

**Review by Noboomta — COMMENTED** [review]
covid_data.py look cool! Great code algorithm. (But no white line after the last line) fair enough...

**Review by lisbono2001 — APPROVED** [review]

**Comment by lisbono2001** [comment]
don't forget to squash and merge rather than merge directly to make our master branch cleaner.

**Comment by Noboomta** [comment]
Thanks for reminding bro, Cheer

**Review by bhatara007 — APPROVED** [review]

**Pull request merged**
