### PR TITLE
Map from google api

### PR DESCRIPTION
**Pull request by Noboomta**

### CODE REVIEW

**Review by lisbono2001 — APPROVED** [review]

**Comment by bhatara007** [comment]
Google Map api no need for our project. if we want to display a clickable Covid summary report page. it can use only .svg map and script in html for that.

**Comment by bhatara007** [comment]
@Noboomta Do you have any problem bro?

**Comment by Noboomta** [comment]
Yes I do have

**Comment by lisbono2001** [comment]
@bhatara007 I think Google-map API is may be used in future like search for country/town and pinned them, I saw in some page that it can change the pin colour by cases.

**Comment by bhatara007** [comment]
@lisbono2001 I see bro but we no need to merge map to master branch now?

**Pull request closed without merging**
