### PR TITLE
Details page & Login page

### PR DESCRIPTION
**Pull request by lisbono2001**

### CODE REVIEW

**Comment by lisbono2001** [comment]
@toey10112 @bhatara007

**Comment by bhatara007** [comment]
Fantastic html page styling dude! our group workflow like a monster haha

**Review by toey10112 — APPROVED** [review]
missing python docs  and test but nice decorate the page

**Comment by bhatara007** [comment]
But we need to refoctor some code and add python-docstring for next iteration I think so.

**Review by bhatara007 — APPROVED** [review]

**Comment by lisbono2001** [comment]
@bhatara007 🔥🔥🔥

**Pull request merged**
