### PR TITLE
Need Help! about apply github authentication

### PR DESCRIPTION
**Pull request by bhatara007**
Please switch to my branch and try to use github auth it's has some a little bit problem when first time I login (redirect to index page) but after that it's fine. if everyone who have any suggestion please comment!

### CODE REVIEW

**Comment by bhatara007** [comment]
@toey10112 @Noboomta @lisbono2001 come on dude!

**Comment by bhatara007** [comment]
So before run a server you need to migrate and install social-auth-app-django by pip install ✌️

**Comment by lisbono2001** [comment]
The code seem okay, no issues now

**Review by lisbono2001 — APPROVED** [review]

**Comment by Noboomta** [comment]
Sorry I forgot to try. Is it works now?

**Comment by Noboomta** [comment]
> The code seem okay, no issues now

Ah ok cheer🍻

**Comment by bhatara007** [comment]
@Noboomta it's too late bro.

**Comment by bhatara007** [comment]
> The code seem okay, no issues now

Thanks for review, the problem has been solved now. Can I merge?

**Comment by Noboomta** [comment]
> @Noboomta it's too late bro.
> 
> 

Haha I did a lot of stuff today😵

**Comment by bhatara007** [comment]
> > @Noboomta it's too late bro.
> 
> Haha I did a lot of stuff today😵
Haha it's fine dude you have THOMAS @lisbono2001

**Comment by toey10112** [comment]
The problem has been solved

**Review by Noboomta — APPROVED** [review]

**Review by toey10112 — APPROVED** [review]
The problem has been solved

**Pull request merged**
